apiVersion: apps/v1 # change version API
kind: ReplicaSet # change resource name
metadata:
  name: my-first-rs
spec:
  replicas: 2
  selector:
    matchLabels: # change here 
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - image: flask-api
        name: hello-kube
        ports:
          - containerPort: 3000
        imagePullPolicy: Never

# selector:
#   matchExpressions:
#     - key: app
#       operator: In       # In, NotIn, Exists, DoesNotExist
#       values:
#         - kubia
