apiVersion: v1 # Descriptor conforms to version v1 of Kubernetes API
kind: Pod # Select Pod resource
metadata:
  name: my-first-pod-testing # The name of the pod
  labels:
    environment: testing # label with key is environment and value is testing
    project: kubernetes-series
spec:
  containers:
    - image: flask-api # Image to create the container
      name: hello-kube # The name of the container
      ports:
        - containerPort: 3000 # The port the app is listening on 
          protocol: TCP
      imagePullPolicy: Never # Tell Kubernetes to use the local image
      env: # pass env to container
        - name: PORT # env name
          value: "3000" # env value (always string)
      command: ["sleep", "9999999"] # thực thi command khi tạo container
      resources: # cấu hình tài nguyên của container
        requests:
          cpu: 15m
          memory: 100Ki
        limits:
          cpu: 100m
          memory: 8Mi
---

apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod-staging
  labels:
    environment: staging # label with key is environment and value is staging
    project: kubernetes-series
spec:
  containers:
    - image: flask-api
      name: hello-kube
      ports:
        - containerPort: 3000
          protocol: TCP
      imagePullPolicy: Never

---
apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod-production
  labels:
    environment: production # label with key is environment and value is production
    project: kubernetes-series
spec:
  containers:
    - image: flask-api
      name: hello-kube
      ports:
        - containerPort: 3000
          protocol: TCP
      imagePullPolicy: Never