apiVersion: apps/v1
kind: Deployment # change here
metadata:
  name: my-first-deployments
spec:
  revisionHistoryLimit: 10 # change here (default is 10)
  replicas: 2
  selector:
    matchLabels:
      app: hello-kube
  template:
    metadata:
      labels:
        app: hello-kube
    spec:
      containers:
      - image: flask-api
        name: hello-kube
        ports:
          - containerPort: 3000
        imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: my-test-deployment-svc
spec:
  type: NodePort
  selector:
    app: hello-kube
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
